### ISSUE TITLE
Connect with Xavier to develop questions for his stakeholders

### ISSUE THREAD

**Issue by joelrip** [CAHealthData/human-services-scoping-plan#6]

**Comment by roughani** [comment]
211 San Diego data update process: 
https://211sandiego.communityos.org/cms/agency_tools

They're using VisionLink's CommunityOS product:
http://www.visionlink.org/communityos-collaboration-tools-for-nonprofits

TO-DO: ask Greg Bloom if he has a relationship with VisionLink (I added him to our GitHub org so we can @ tag him in issues after he clicks confirmation link).
